version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mta-bustracker-rt"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1eiqpjdhvewy3"
s3_prefix = "mta-bustracker-rt"
region = "us-east-1"
profile = "bus-tracker"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "IdentityNameParameter=\"\""
image_repositories = []
